export const usStates = [
  { id: 0, data: "Alabama" },
  { id: 1, data: "Alaska" },
  { id: 2, data: "Arizona" },
  { id: 3, data: "Arkansas" },
  { id: 4, data: "California" },
  { id: 5, data: "Colorado" },
  { id: 6, data: "Connecticut" },
  { id: 7, data: "Delaware" },
  { id: 8, data: "Florida" },
  { id: 9, data: "Georgia" },
  { id: 10, data: "Hawaii" },
  { id: 11, data: "Idaho" },
  { id: 12, data: "Illinois" },
  { id: 13, data: "Indiana" },
  { id: 14, data: "Iowa" },
  { id: 15, data: "Kansas" },
  { id: 16, data: "Kentucky" },
  { id: 17, data: "Louisiana" },
  { id: 18, data: "Maine" },
  { id: 19, data: "Maryland" },
  { id: 20, data: "Massachusetts" },
  { id: 21, data: "Michigan" },
  { id: 22, data: "Minnesota" },
  { id: 23, data: "Mississippi" },
  { id: 24, data: "Missouri" },
  { id: 25, data: "Montana" },
  { id: 26, data: "Nebraska" },
  { id: 27, data: "Nevada" },
  { id: 28, data: "New Hampshire" },
  { id: 29, data: "New Jersey" },
  { id: 30, data: "New Mexico" },
  { id: 31, data: "New York" },
  { id: 32, data: "North Carolina" },
  { id: 33, data: "North Dakota" },
  { id: 34, data: "Ohio" },
  { id: 35, data: "Oklahoma" },
  { id: 36, data: "Oregon" },
  { id: 37, data: "Pennsylvania" },
  { id: 38, data: "Rhode Island" },
  { id: 39, data: "South Carolina" },
  { id: 40, data: "South Dakota" },
  { id: 41, data: "Tennessee" },
  { id: 42, data: "Texas" },
  { id: 43, data: "Utah" },
  { id: 44, data: "Vermont" },
  { id: 45, data: "Virginia" },
  { id: 46, data: "Washington" },
  { id: 47, data: "West Virginia" },
  { id: 48, data: "Wisconsin" },
  { id: 49, data: "Wyoming" },
];

export const latinText = [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
  "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
  "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
];

export const multiSelectData = [
  { id: 0, data: "Eaten Chipotle more than 3 times in one week?" },
  { id: 1, data: "Seen a shark?" },
  { id: 2, data: "Ordered a couch online?" },
  { id: 3, data: "Accidentally hooked a seagull with a fishing rod?" },
  { id: 4, data: "Regretfully drank alcohol on a Sunday?" },
  { id: 5, data: "Fell asleep in a hammock?" },
  {
    id: 6,
    data: "Walked to an event and ended up being drenched in your own sweat?",
  },
  { id: 7, data: "Lost a bet?" },
];

export const radioButtonData = [
  { index: 0, label: "Small" },
  { index: 1, label: "Medium" },
];
